// <auto-generated />
namespace AASC.Partner.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetDepartmentHeadEmployeeIdNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetDepartmentHeadEmployeeIdNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201604261820102_SetDepartmentHeadEmployeeIdNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
